deployments:
- name: "Arbo - MultiClient"
  version: null
  tags: []
  concurrency_limit: null
  description: null
  entrypoint: flows/arbo_flow.py:arbo_pipeline
  flow_name: "Arbo to ClickHouse"
  parameters:
    date_start: null
    date_stop: null
  path: /app
  work_pool:
    name: default
  schedule: null
  timestamp: '2026-03-13T00:00:00.000000+00:00'
